### ISSUE TITLE
Macros broken since 8.0.1

### ISSUE THREAD

**Issue by Soeroah** [Tschebel/CollectMe#9]
The macros to summon random mounts seem to be broken as of the new patch. Profile data is still working fine, and doesn't seem to have been lost, but the macros that last week were able to summon a random mount from all those you checked off seem completely non-functional now.

**Comment by TumblrLee** [comment]
The keybind I had set to random mount doesn't work either.  As of now I can't manage to get this to work on any of my toons

**Comment by JimBim89** [comment]
Thanks for the report, this will be fixed in the next patch.
